# Generated by Django 4.2.7 on 2023-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Functions',
                'ordering': ('-id',),
            },
        ),
    ]
