# Generated by Django 4.2.7 on 2023-11-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_blogmodel_category_alter_blogmodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
    ]
